package domain;
// Generated 15-feb-2018 15:31:18 by Hibernate Tools 5.2.8.Final

/**
 * Usuarios generated by hbm2java
 */
@SuppressWarnings("serial")
public class Usuarios implements java.io.Serializable {

	private Integer idUsuario;
	private String username;
	private String password;
	private String token;

	public Usuarios() {
	}

	public Usuarios(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
